services:
  api:
    build:
      context: ./backend      
      dockerfile: Dockerfile
    container_name: agrogear-api
    restart: always
    networks:
      - shared-proxy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agrogear.rule=Host(`api.satna.hu`) && PathPrefix(`/agrogear`)"
      - "traefik.http.routers.agrogear.entrypoints=websecure"
      - "traefik.http.routers.agrogear.tls.certresolver=myresolver"
      - "traefik.http.services.agrogear.loadbalancer.server.port=3000"

      - "traefik.http.middlewares.strip-agrogear.stripprefix.prefixes=/agrogear"
      - "traefik.http.routers.agrogear.middlewares=strip-agrogear"

networks:
  shared-proxy:
    external: true